/** Candy palette — lab choice & lab upload onboarding screens */
export const LabOnboardingColors = {
  background: '#fef7ff',
  surface: '#fef7ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#fbf2fb',
  surfaceContainer: '#f8eef8',
  surfaceContainerHigh: '#f2e8f2',
  surfaceContainerHighest: '#ece2ec',
  surfaceVariant: '#f2e8f2',
  primary: '#e040a0',
  primaryContainer: '#f080c0',
  primaryFixed: '#ffd6ee',
  onPrimary: '#ffffff',
  onBackground: '#2e1a28',
  onSurface: '#2e1a28',
  onSurfaceVariant: '#604868',
  secondary: '#7c52aa',
  secondaryContainer: '#eedcff',
  secondaryFixed: '#eedcff',
  tertiary: '#0096cc',
  tertiaryContainer: '#40c0ee',
  tertiaryFixed: '#c8eaff',
  outline: '#907898',
  outlineVariant: '#dcc8e0',
  cardBorder: '#f2e5eb',
  choiceBorder: '#f2e5eb',
  choiceActiveBg: '#fff0f7',
};

export const LabChoiceColors = {
  background: '#fffbff',
  surface: '#fffbff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#fdf1f6',
  surfaceContainer: '#f8ebf1',
  surfaceContainerHigh: '#f2e5eb',
  surfaceContainerHighest: '#ecdfe5',
  primary: '#e040a0',
  primaryContainer: '#ffe4f1',
  onPrimary: '#ffffff',
  onSurface: '#1f1a1c',
  onSurfaceVariant: '#51434a',
};
