import type { GlucoseReading } from '../types/glucoseReading';

function daysAgo(days: number, hour: number, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

/** Demo rows for glucose history UI when no real readings exist yet. */
export const DUMMY_GLUCOSE_READINGS: GlucoseReading[] = [
  {
    id: -1,
    patient_id: 0,
    value_mgdl: 118,
    reading_type: 'fasting',
    measured_at: daysAgo(0, 7, 15),
    status: 'normal',
    notes: 'Before breakfast',
    source: 'manual',
    created_at: daysAgo(0, 7, 15),
  },
  {
    id: -2,
    patient_id: 0,
    value_mgdl: 162,
    reading_type: 'post_meal',
    measured_at: daysAgo(0, 13, 40),
    status: 'elevated',
    notes: '2h after lunch',
    source: 'manual',
    created_at: daysAgo(0, 13, 40),
  },
  {
    id: -3,
    patient_id: 0,
    value_mgdl: 104,
    reading_type: 'fasting',
    measured_at: daysAgo(1, 7, 5),
    status: 'normal',
    notes: null,
    source: 'manual',
    created_at: daysAgo(1, 7, 5),
  },
  {
    id: -4,
    patient_id: 0,
    value_mgdl: 148,
    reading_type: 'post_meal',
    measured_at: daysAgo(1, 19, 20),
    status: 'elevated',
    notes: 'After dinner',
    source: 'manual',
    created_at: daysAgo(1, 19, 20),
  },
  {
    id: -5,
    patient_id: 0,
    value_mgdl: 96,
    reading_type: 'fasting',
    measured_at: daysAgo(2, 6, 50),
    status: 'normal',
    notes: null,
    source: 'manual',
    created_at: daysAgo(2, 6, 50),
  },
  {
    id: -6,
    patient_id: 0,
    value_mgdl: 212,
    reading_type: 'random',
    measured_at: daysAgo(3, 15, 10),
    status: 'high',
    notes: 'Felt thirsty — recheck advised',
    source: 'manual',
    created_at: daysAgo(3, 15, 10),
  },
  {
    id: -7,
    patient_id: 0,
    value_mgdl: 112,
    reading_type: 'fasting',
    measured_at: daysAgo(4, 7, 30),
    status: 'normal',
    notes: null,
    source: 'manual',
    created_at: daysAgo(4, 7, 30),
  },
  {
    id: -8,
    patient_id: 0,
    value_mgdl: 134,
    reading_type: 'bedtime',
    measured_at: daysAgo(5, 22, 0),
    status: 'normal',
    notes: 'Before sleep',
    source: 'manual',
    created_at: daysAgo(5, 22, 0),
  },
  {
    id: -9,
    patient_id: 0,
    value_mgdl: 68,
    reading_type: 'fasting',
    measured_at: daysAgo(6, 6, 45),
    status: 'low',
    notes: 'Ate a snack afterward',
    source: 'manual',
    created_at: daysAgo(6, 6, 45),
  },
  {
    id: -10,
    patient_id: 0,
    value_mgdl: 155,
    reading_type: 'post_meal',
    measured_at: daysAgo(7, 14, 5),
    status: 'elevated',
    notes: null,
    source: 'manual',
    created_at: daysAgo(7, 14, 5),
  },
];
