#!/usr/bin/env python3
"""
Create/update backend .env for Zoom telehealth and run DB migration.

Usage:
  python setup_zoom.py
  python setup_zoom.py --client-id YOUR_ID --client-secret YOUR_SECRET
"""

from __future__ import annotations

import argparse
import re
import secrets
import socket
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent
ENV_FILE = BACKEND_DIR / ".env"
ENV_TEMPLATE = BACKEND_DIR / "env.template"
LAN_IP = "192.168.1.9"


def detect_lan_ip() -> str:
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("8.8.8.8", 80))
            return s.getsockname()[0]
    except OSError:
        return LAN_IP


def parse_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    data: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        data[key.strip()] = value.strip()
    return data


def write_env(values: dict[str, str]) -> None:
    lines: list[str] = [
        "# Gluco-track backend — generated by setup_zoom.py",
        "# Zoom app: https://marketplace.zoom.us/develop/create",
        "# Type: General app → User-managed OAuth",
        "# Redirect URL must match ZOOM_REDIRECT_URI exactly.",
        "",
        f"DATABASE_URL={values.get('DATABASE_URL', 'sqlite:///./healthcare.db')}",
        f"SECRET_KEY={values.get('SECRET_KEY', secrets.token_urlsafe(32))}",
        "ALGORITHM=HS256",
        "ACCESS_TOKEN_EXPIRE_MINUTES=1440",
        "",
        f"ZOOM_CLIENT_ID={values.get('ZOOM_CLIENT_ID', '')}",
        f"ZOOM_CLIENT_SECRET={values.get('ZOOM_CLIENT_SECRET', '')}",
        f"ZOOM_REDIRECT_URI={values.get('ZOOM_REDIRECT_URI', '')}",
        f"ZOOM_OAUTH_FRONTEND_REDIRECT={values.get('ZOOM_OAUTH_FRONTEND_REDIRECT', '')}",
        f"ZOOM_HOST_USER_ID={values.get('ZOOM_HOST_USER_ID', '')}",
        "",
        "# Optional Server-to-Server fallback (scheduled meetings without OAuth host):",
        f"ZOOM_ACCOUNT_ID={values.get('ZOOM_ACCOUNT_ID', '')}",
        f"ZOOM_USER_ID={values.get('ZOOM_USER_ID', 'me')}",
        "",
    ]
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {ENV_FILE}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Configure Zoom OAuth for Gluco-track")
    parser.add_argument("--client-id", help="Zoom OAuth Client ID")
    parser.add_argument("--client-secret", help="Zoom OAuth Client Secret")
    parser.add_argument("--lan-ip", default=detect_lan_ip(), help="PC LAN IP for phone testing")
    args = parser.parse_args()

    ip = args.lan_ip
    existing = parse_env(ENV_FILE) if ENV_FILE.exists() else parse_env(ENV_TEMPLATE)

    client_id = args.client_id or existing.get("ZOOM_CLIENT_ID", "")
    client_secret = args.client_secret or existing.get("ZOOM_CLIENT_SECRET", "")

    if not client_id:
        client_id = input("Zoom Client ID (from marketplace.zoom.us): ").strip()
    if not client_secret:
        client_secret = input("Zoom Client Secret: ").strip()

    origins = (
        f"http://localhost:8084,http://127.0.0.1:8084,"
        f"http://{ip}:8084,http://localhost:8000,http://{ip}:8000"
    )

    values = {
        **existing,
        "DATABASE_URL": existing.get("DATABASE_URL") or "sqlite:///./healthcare.db",
        "SECRET_KEY": existing.get("SECRET_KEY") or secrets.token_urlsafe(32),
        "ALLOWED_ORIGINS": origins,
        "ZOOM_CLIENT_ID": client_id,
        "ZOOM_CLIENT_SECRET": client_secret,
        "ZOOM_REDIRECT_URI": f"http://{ip}:8000/zoom/oauth/callback",
        "ZOOM_OAUTH_FRONTEND_REDIRECT": f"http://{ip}:8084",
    }
    write_env(values)

    print("\nAdd this Redirect URL in your Zoom app settings:")
    print(f"  {values['ZOOM_REDIRECT_URI']}")
    print("\nRequired OAuth scopes:")
    print("  user:read, meeting:write:meeting, meeting:read:meeting")
    print("\nRunning Zoom DB migration...")
    from migrate_add_zoom_oauth import migrate

    migrate()

    if client_id and client_secret:
        print("\nZoom is configured. Restart backend: python run.py")
        print("Then in the app: Dashboard → Call Doctor → Connect Zoom (doctor account).")
    else:
        print("\nAdd ZOOM_CLIENT_ID and ZOOM_CLIENT_SECRET to .env, then restart backend.")


if __name__ == "__main__":
    main()
